language: node_js
node_js:
  - "8"
install:
  - npm install
script:
  - 'if [ "$(node_modules/.bin/prettier --single-quote "**/*.js" --list-different --ignore=./node_modules/** ./dist/**)" ]; then exit 1; fi'
  - npm run test:coverage
after_success:
  - npm run coveralls
